import type { RoutineItem } from './types';

/** Authenticated morning & evening adhkar + daily duas, inspired by Hisnul Muslim / Sunnah sources. */

export const MORNING_AZKAR: RoutineItem[] = [
  {
    id: 'm-ayat-kursi',
    category: 'morning',
    title: 'Ayat al-Kursi',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allahu la ilaha illa Huwa, Al-Hayyul-Qayyum...',
    translation: 'Allah — there is no god but Him, the Ever-Living, the Sustainer of all. (Qur\'an 2:255)',
    count: 1,
    reference: 'Al-Hakim / At-Tabarani — protection until evening. Hisnul Muslim 75',
    benefit: 'Whoever recites it in the morning is protected until evening.',
  },
  {
    id: 'm-three-quls',
    category: 'morning',
    title: 'The Three Quls (Ikhlas, Falaq, Nas)',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
    transliteration: 'Qul huwa Allahu ahad… Qul a\'udhu bi Rabbil-falaq… Qul a\'udhu bi Rabbin-nas…',
    translation: 'Recite Surah al-Ikhlas, al-Falaq, and an-Nas completely.',
    count: 3,
    reference: 'Abu Dawud 5082, At-Tirmidhi 5/567 — Hisnul Muslim 76',
    benefit: 'Reciting these three times in the morning and evening suffices against everything.',
  },
  {
    id: 'm-sayyid-istighfar',
    category: 'morning',
    title: 'Sayyid al-Istighfar',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana \'abduka...',
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant… so forgive me, for none forgives sins except You.',
    count: 1,
    reference: 'Sahih al-Bukhari 6306 — Hisnul Muslim 79',
    benefit: 'Whoever says it with conviction in the morning and dies that day enters Paradise.',
  },
  {
    id: 'm-asbahna-mulk',
    category: 'morning',
    title: 'Asbahna wa asbahal-mulku lillah',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, wal-hamdu lillah, la ilaha illallahu wahdahu la sharika lah...',
    translation: 'We have entered the morning and with it all dominion belongs to Allah, and all praise is for Allah...',
    count: 1,
    reference: 'Sahih Muslim 2723 — Hisnul Muslim 77',
  },
  {
    id: 'm-bika-asbahna',
    category: 'morning',
    title: 'Allahumma bika asbahna',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilaykan-nushur.',
    translation: 'O Allah, by You we enter the morning, by You we enter the evening, by You we live, by You we die, and to You is the resurrection.',
    count: 1,
    reference: 'Abu Dawud 5068 — Hisnul Muslim',
  },
  {
    id: 'm-bismillah-la-yadurru',
    category: 'morning',
    title: 'Bismillah — protection from harm',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'as-mihi shay\'un fil-ardi wa la fis-sama\', wa huwas-Sami\'ul-\'Alim.',
    translation: 'In the Name of Allah, with Whose Name nothing can cause harm in the earth nor in the heavens, and He is the All-Hearing, the All-Knowing.',
    count: 3,
    reference: 'Abu Dawud 4/323, At-Tirmidhi 5/465 — Hisnul Muslim 86',
    benefit: 'Whoever says it 3× in the morning will not be afflicted by calamity before evening.',
  },
  {
    id: 'm-ya-hayyu',
    category: 'morning',
    title: 'Ya Hayyu Ya Qayyum',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: 'Ya Hayyu Ya Qayyum, bi-rahmatika astaghith, aslih li sha\'ni kullah, wa la takilni ila nafsi tarfata \'ayn.',
    translation: 'O Ever-Living, O Sustainer, by Your mercy I seek help. Set right all my affairs and do not leave me to myself even for the blink of an eye.',
    count: 1,
    reference: 'An-Nasa\'i — Hisnul Muslim 88',
  },
  {
    id: 'm-hasbiyallah',
    category: 'morning',
    title: 'Hasbiyallahu',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۚ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Hasbiyallahu la ilaha illa Huwa, \'alayhi tawakkaltu wa Huwa Rabbul-\'Arshil-\'Azim.',
    translation: 'Allah is sufficient for me; there is no god but Him. In Him I put my trust, and He is the Lord of the Mighty Throne.',
    count: 7,
    reference: 'Abu Dawud 4/321 — Hisnul Muslim 83',
    benefit: 'Allah will suffice whoever recites this 7 times in whatever concerns them.',
  },
  {
    id: 'm-subhanallah',
    category: 'morning',
    title: 'Subhanallahi wa bihamdihi',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhanallahi wa bihamdihi',
    translation: 'Glory is to Allah and praise is to Him.',
    count: 100,
    reference: 'Sahih al-Bukhari 6405, Sahih Muslim 2691 — Hisnul Muslim 91',
    benefit: 'Sins forgiven even if like the foam of the sea; none surpasses you on Judgment Day except one who said more.',
  },
  {
    id: 'm-tawhid-10',
    category: 'morning',
    title: 'La ilaha illallah wahdahu (10×)',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa \'ala kulli shay\'in qadir.',
    translation: 'None has the right to be worshipped but Allah alone, without partner. His is the dominion and His is the praise, and He is Able to do all things.',
    count: 10,
    reference: 'An-Nasa\'i; Ahmad — Hisnul Muslim 92',
    benefit: 'Reward of freeing ten slaves; protection from Shaytan until evening.',
  },
  {
    id: 'm-ilman-nafian',
    category: 'morning',
    title: 'Beneficial knowledge & provision',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: 'Allahumma inni as\'aluka \'ilman nafi\'an, wa rizqan tayyiban, wa \'amalan mutaqabbalan.',
    translation: 'O Allah, I ask You for beneficial knowledge, wholesome provision, and accepted deeds.',
    count: 1,
    reference: 'Ibn Majah 925 — said after Fajr. Hisnul Muslim 95',
  },
  {
    id: 'm-salawat',
    category: 'morning',
    title: 'Salawat upon the Prophet ﷺ',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ',
    transliteration: 'Allahumma salli wa sallim \'ala nabiyyina Muhammad.',
    translation: 'O Allah, send prayers and peace upon our Prophet Muhammad.',
    count: 10,
    reference: 'At-Tabarani — Hisnul Muslim 98',
    benefit: 'Whoever sends blessings 10× morning and evening will have the Prophet\'s intercession.',
  },
];

export const EVENING_AZKAR: RoutineItem[] = [
  {
    id: 'e-ayat-kursi',
    category: 'evening',
    title: 'Ayat al-Kursi',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allahu la ilaha illa Huwa, Al-Hayyul-Qayyum...',
    translation: 'Allah — there is no god but Him, the Ever-Living, the Sustainer of all. (Qur\'an 2:255)',
    count: 1,
    reference: 'Al-Hakim / At-Tabarani — Hisnul Muslim 75',
    benefit: 'Whoever recites it in the evening is protected until morning.',
  },
  {
    id: 'e-three-quls',
    category: 'evening',
    title: 'The Three Quls (Ikhlas, Falaq, Nas)',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
    transliteration: 'Qul huwa Allahu ahad… Qul a\'udhu bi Rabbil-falaq… Qul a\'udhu bi Rabbin-nas…',
    translation: 'Recite Surah al-Ikhlas, al-Falaq, and an-Nas completely.',
    count: 3,
    reference: 'Abu Dawud 5082, At-Tirmidhi — Hisnul Muslim 76',
    benefit: 'They will suffice you against everything.',
  },
  {
    id: 'e-sayyid-istighfar',
    category: 'evening',
    title: 'Sayyid al-Istighfar',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta Rabbi la ilaha illa anta...',
    translation: 'O Allah, You are my Lord… so forgive me, for none forgives sins except You.',
    count: 1,
    reference: 'Sahih al-Bukhari 6306 — Hisnul Muslim 79',
    benefit: 'Whoever says it with conviction at night and dies that night enters Paradise.',
  },
  {
    id: 'e-amsayna-mulk',
    category: 'evening',
    title: 'Amsayna wa amsal-mulku lillah',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Amsayna wa amsal-mulku lillah, wal-hamdu lillah...',
    translation: 'We have entered the evening and with it all dominion belongs to Allah...',
    count: 1,
    reference: 'Sahih Muslim 2723 — Hisnul Muslim 77',
  },
  {
    id: 'e-bika-amsayna',
    category: 'evening',
    title: 'Allahumma bika amsayna',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    transliteration: 'Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu, wa ilaykal-masir.',
    translation: 'O Allah, by You we enter the evening, by You we enter the morning, by You we live, by You we die, and to You is the return.',
    count: 1,
    reference: 'Abu Dawud 5079 — Hisnul Muslim',
  },
  {
    id: 'e-bismillah-la-yadurru',
    category: 'evening',
    title: 'Bismillah — protection from harm',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'as-mihi shay\'un fil-ardi wa la fis-sama\', wa huwas-Sami\'ul-\'Alim.',
    translation: 'In the Name of Allah, with Whose Name nothing can cause harm...',
    count: 3,
    reference: 'Abu Dawud, At-Tirmidhi — Hisnul Muslim 86',
    benefit: 'Whoever says it 3× in the evening will not be overtaken by calamity before morning.',
  },
  {
    id: 'e-audhu-kalimat',
    category: 'evening',
    title: 'A\'udhu bi kalimatillah (evening)',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'udhu bi kalimatillahit-tammati min sharri ma khalaq.',
    translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    count: 3,
    reference: 'Sahih Muslim 2708; Ahmad — Hisnul Muslim 97',
    benefit: 'Evening-specific: protects from insect stings / harm that night.',
  },
  {
    id: 'e-ya-hayyu',
    category: 'evening',
    title: 'Ya Hayyu Ya Qayyum',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: 'Ya Hayyu Ya Qayyum, bi-rahmatika astaghith...',
    translation: 'O Ever-Living, O Sustainer, by Your mercy I seek help...',
    count: 1,
    reference: 'An-Nasa\'i — Hisnul Muslim 88',
  },
  {
    id: 'e-hasbiyallah',
    category: 'evening',
    title: 'Hasbiyallahu',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۚ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Hasbiyallahu la ilaha illa Huwa...',
    translation: 'Allah is sufficient for me; there is no god but Him...',
    count: 7,
    reference: 'Abu Dawud — Hisnul Muslim 83',
  },
  {
    id: 'e-subhanallah',
    category: 'evening',
    title: 'Subhanallahi wa bihamdihi',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhanallahi wa bihamdihi',
    translation: 'Glory is to Allah and praise is to Him.',
    count: 100,
    reference: 'Sahih al-Bukhari, Sahih Muslim — Hisnul Muslim 91',
  },
  {
    id: 'e-tawhid-10',
    category: 'evening',
    title: 'La ilaha illallah wahdahu (10×)',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah...',
    translation: 'None has the right to be worshipped but Allah alone...',
    count: 10,
    reference: 'An-Nasa\'i; Ahmad — Hisnul Muslim 92',
  },
  {
    id: 'e-salawat',
    category: 'evening',
    title: 'Salawat upon the Prophet ﷺ',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ',
    transliteration: 'Allahumma salli wa sallim \'ala nabiyyina Muhammad.',
    translation: 'O Allah, send prayers and peace upon our Prophet Muhammad.',
    count: 10,
    reference: 'At-Tabarani — Hisnul Muslim 98',
  },
];

export const DAILY_DUAS: RoutineItem[] = [
  {
    id: 'd-waking',
    category: 'dua',
    title: 'Upon waking up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur.',
    translation: 'All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.',
    count: 1,
    reference: 'Sahih al-Bukhari 6312, Sahih Muslim 2711 — Hisnul Muslim 1',
  },
  {
    id: 'd-sleeping',
    category: 'dua',
    title: 'Before sleeping',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya.',
    translation: 'In Your name, O Allah, I die and I live.',
    count: 1,
    reference: 'Sahih al-Bukhari 6314 — Hisnul Muslim',
  },
  {
    id: 'd-toilet-enter',
    category: 'dua',
    title: 'Before entering the toilet',
    arabic: 'بِسْمِ اللَّهِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    transliteration: 'Bismillah. Allahumma inni a\'udhu bika minal-khubthi wal-khaba\'ith.',
    translation: 'In the Name of Allah. O Allah, I seek refuge in You from the male and female unclean spirits.',
    count: 1,
    reference: 'Sahih al-Bukhari 142, Sahih Muslim 375 — Hisnul Muslim',
  },
  {
    id: 'd-toilet-exit',
    category: 'dua',
    title: 'After leaving the toilet',
    arabic: 'غُفْرَانَكَ',
    transliteration: 'Ghufranaka.',
    translation: 'I ask You (Allah) for forgiveness.',
    count: 1,
    reference: 'Abu Dawud, At-Tirmidhi — Hisnul Muslim',
  },
  {
    id: 'd-before-eat',
    category: 'dua',
    title: 'Before eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah.',
    translation: 'In the Name of Allah. (If forgotten at the start: Bismillahi fi awwalihi wa akhirihi.)',
    count: 1,
    reference: 'Abu Dawud, At-Tirmidhi — Hisnul Muslim 69',
  },
  {
    id: 'd-after-eat',
    category: 'dua',
    title: 'After eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: 'Alhamdu lillahil-ladhi at\'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah.',
    translation: 'All praise is for Allah who fed me this and provided it for me without any might or power from myself.',
    count: 1,
    reference: 'Abu Dawud, At-Tirmidhi, Ibn Majah — Hisnul Muslim 70',
  },
  {
    id: 'd-leave-home',
    category: 'dua',
    title: 'When leaving home',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismillah, tawakkaltu \'alallah, wa la hawla wa la quwwata illa billah.',
    translation: 'In the Name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    count: 1,
    reference: 'Abu Dawud, At-Tirmidhi — Hisnul Muslim 10',
    benefit: 'It is said: you are guided, defended, and protected; Shaytan turns away.',
  },
  {
    id: 'd-enter-home',
    category: 'dua',
    title: 'When entering home',
    arabic: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَىٰ رَبِّنَا تَوَكَّلْنَا',
    transliteration: 'Bismillahi walajna, wa bismillahi kharajna, wa \'ala Rabbina tawakkalna.',
    translation: 'In the Name of Allah we enter, in the Name of Allah we leave, and upon our Lord we place our trust.',
    count: 1,
    reference: 'Abu Dawud — Hisnul Muslim 11',
  },
  {
    id: 'd-travel',
    category: 'dua',
    title: 'When travelling / mounting',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
    transliteration: 'Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina la-munqalibun.',
    translation: 'Glory to Him Who has subjected this to us, and we could never have it by our efforts. And surely, to our Lord we shall return.',
    count: 1,
    reference: 'Qur\'an 43:13-14; Abu Dawud, At-Tirmidhi — Hisnul Muslim',
  },
  {
    id: 'd-anxiety',
    category: 'dua',
    title: 'When anxious or distressed',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
    transliteration: 'Allahumma inni a\'udhu bika minal-hammi wal-hazan...',
    translation: 'O Allah, I seek refuge in You from anxiety and sorrow, from weakness and laziness, from cowardice and miserliness, and from being overcome by debt and overpowered by men.',
    count: 1,
    reference: 'Sahih al-Bukhari 6369 — Hisnul Muslim',
  },
];

export const ALL_ROUTINE_ITEMS: RoutineItem[] = [
  ...MORNING_AZKAR,
  ...EVENING_AZKAR,
  ...DAILY_DUAS,
];

export type RoutineSection = 'morning' | 'evening' | 'duas';

export const ROUTINE_SECTION_META: Record<
  RoutineSection,
  { label: string; subtitle: string; timing: string }
> = {
  morning: {
    label: 'Morning Azkar',
    subtitle: 'أذكار الصباح',
    timing: 'Best after Fajr until sunrise (makeup until Dhuhr OK)',
  },
  evening: {
    label: 'Evening Azkar',
    subtitle: 'أذكار المساء',
    timing: 'Best after Asr until Maghrib (makeup later OK)',
  },
  duas: {
    label: 'Daily Duas',
    subtitle: 'أدعية يومية',
    timing: 'Throughout the day — wake, eat, leave home, sleep…',
  },
};
